### ISSUE TITLE
Navigation menu covers up the article

### ISSUE THREAD

**Issue by mcandre** [duplode/duplode.github.io#3]
"The Life Monadic" navigation menu covers up a large part of the article, making it hard to read.

Please consider removing 'position: fixed' from the CSS settings, and placing it at the top of the page, as most other websites do.

**Comment by duplode** [comment]
Fixed - the Pure sytlesheet was being loaded from Yahoo's HTTP-only CDN, and so the layout was garbled over HTTPS. Thanks for the report!
